import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from 'components/layout/Header';
import ThemeProvider from 'lib/context/ThemeProvider';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'AI Assistant',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en' className={inter.variable} suppressHydrationWarning>
      <body className='min-h-screen antialiased'>
        <ThemeProvider
          attribute='class'
          defaultTheme='black'
          enableSystem
          disableTransitionOnChange
        >
          <div className=''>
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
